Repository gdscgcu/Learn-with-Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#2 Weather App
  homepage.dart
  landingpage.dart
  main.dart
  routes.dart
Labels: hacktoberfest-accepted

#4 Create List_Comprehensions.py
  Python/List_Comprehensions.py
Labels: hacktoberfest-accepted

#3 Data Structures
  Data-Structures/GeneralFlexibleArray.cpp
Labels: help wanted, hacktoberfest-accepted

#14 Find the number of pairs whoes sum is equal to the given number
  Data-Structures/count-pairs-with-given-sum.cpp
Labels: help wanted, hacktoberfest-accepted

#13 Create Counting_Sort.py
  Python/Counting_Sort.py
Labels: hacktoberfest-accepted

#8 Prime Number Python Program
  Python/primenumber.py
Labels: hacktoberfest-accepted

#9 Create alarm.py
  Python/alarm.py
Labels: hacktoberfest-accepted

#7 Create validation_password_creation_solution.py
  Python/validation_password_creation_solution.py
Labels: hacktoberfest-accepted

#19 Added code for SinglyLinkedList in java
  Data-Structures/Java/LinkedList.java
  Data-Structures/Java/List.java
Labels: enhancement, hacktoberfest-accepted

#26 Digital clock
  digital_clock.js
Labels: hacktoberfest-accepted

#24 Graph in C++ Added
  Data-Structures/Graph/Graph.h
  Data-Structures/Graph/Main.cpp
Labels: hacktoberfest-accepted

#23 Create Radixsort.py
  Python/Radixsort.py
Labels: hacktoberfest-accepted

#25 Add Fibonacci Java
  Data-Structures/Java/Fibonacci.java
Labels: hacktoberfest-accepted

#29 Create Password_validotor.py
  Python/Password_validotor.py
Labels: hacktoberfest-accepted

#43 Create bubbleSort.cpp
  Data-Structures/bubbleSort.cpp
Labels: hacktoberfest-accepted

#42 created cat & non-cat classifier
  Python/cat_classifier_logistic_regression.ipynb
Labels: hacktoberfest-accepted

#41 Create counting_sort.cpp
  Data-Structures/counting_sort.cpp
Labels: hacktoberfest-accepted

#35 Added One ML Project
  Machine learninig/Image to Sketch/ImagetoSketch.ipynb
  Machine learninig/Image to Sketch/apple.jpg
Labels: hacktoberfest-accepted

#28 Create calculator.js
  calculator.js
Labels: hacktoberfest-accepted

#40 Create Bubble_Sort.java
  Data-Structures/Java/Bubble_Sort.java
Labels: enhancement, hacktoberfest-accepted

#48 Circular Stack List
  Data-Structures/CircularStackList.cpp
Labels: hacktoberfest-accepted

#58 created Tic-Tac-Toe.py
  Python/Tic-Tac-Toe.py
  Python/text-to-speech.py
Labels: hacktoberfest-accepted

#57 Added Caching RBG colors in java
  Java/Caching Colors.java
Labels: hacktoberfest-accepted

#56 Hacktoberfest october
  CoderbyteQuestion/ArrayChallange16Q2.js
  CoderbyteQuestion/ArrayChallange17.js
  CoderbyteQuestion/ArrayChallenge16Q3.js
  CoderbyteQuestion/BinarySearch.rb
  CoderbyteQuestion/MathChallange17.js
  CoderbyteQuestion/Operating system interview questions with answers .pdf
  CoderbyteQuestion/PF concepts and Interview questions.pdf
  CoderbyteQuestion/StringChallengeTest16Q1.py
  Text-Editor-master/README.md
  Text-Editor-master/Text_Editor.cpp
Labels: hacktoberfest-accepted

#55 String Split and Join
  Python/String_Split_&_Join.py
Labels: hacktoberfest-accepted

#54 BFS Tree Algo in C++
  Data-Structures/BFS-Algorithim-in-C++.cpp.txt
Labels: hacktoberfest-accepted

#53 Heap-Data-Structure-in-C++-added
  Data-Structures/Heap-in-C++/creation_heap.cpp
  Data-Structures/Heap-in-C++/insertion_and_deletion_in_heap.cpp
  Data-Structures/Heap-in-C++/kSlosest.cpp
  Data-Structures/Heap-in-C++/kthSmallest.cpp
  Data-Structures/Heap-in-C++/kthlargest.cpp
  Data-Structures/Heap-in-C++/sortKsorted.cpp
Labels: hacktoberfest-accepted

#52 Create NPAIRS.java
  Data-Structures/Java/NPAIRS.java
Labels: hacktoberfest-accepted

#51 Create RomanNumeral Converter
  Python/RomanNumeral Converter
Labels: hacktoberfest-accepted

#46 Create Number of Steps to Reduce a Number to Zero-C++
  Number of Steps to Reduce a Number to Zero-C++
Labels: hacktoberfest-accepted

#12 Create Difference_Table (Integer).cpp
  C++/Difference_Table (Integer).cpp
Labels: hacktoberfest-accepted
